trigger: none

pool:
  vmImage: ubuntu-latest

variables:
  - group: Infrastructure  

jobs:
- job:
  displayName: Deploy Infrastructure
  steps:
  - task: AzureResourceManagerTemplateDeployment@3
    inputs:
      connectedServiceName: $(ServiceConnectionName)
      location: $(DeploymentDefaultLocation)
      resourceGroupName: $(ResourceGroupName)
      csmFile: main.bicep