trigger: none

pool:
  vmImage: ubuntu-latest

  variables:
    - group: Infrastructure

jobs:
- job:
  steps:
  - task: AzureResourceManagerTemplateDeployment@3
    inputs:
      connectedServiceName: Pay-As-You-Go (51481efe-772a-49e5-a013-9e3001e18be8)
      location: West Europe
      resourceGroupName: Test
      csmFile: main.bicep