name: Deploy Infrastructure

parameters:
- name: resourceGroup
  displayName: ETL Resource Group
  type: string
  default: ETLTest
- name: region
  displayName: ETL Region
  type: string
  default: East US 2
  values:
  - East US
  - East US 2
  - West US
  - West US 2
- name: cosmosAccountName
  displayName: Cosmos Account Name
  type: string
  default: AzurePetStore
- name: cosmosDatabaseName
  displayName: Cosmos Database Name
  type: string
  default: E-Commerce
- name: cosmosContainerName
  displayName: Cosmos Container Name
  type: string
  default: Orders
  
trigger: none

pool:
  vmImage: ubuntu-latest

variables:
  - group: Infrastructure  

jobs:
- job:
  displayName: Deploy Infrastructure
  steps:
  - task: AzureResourceManagerTemplateDeployment@3
    inputs:
      connectedServiceName: $(ServiceConnectionName)
      location: $(DeploymentDefaultLocation)
      resourceGroupName: $(ResourceGroupName)
      csmFile: main.bicep