# Replace {subscriptionId} and {resourceGroupName} with your own values
subscriptionId: $(subscriptionId)
resourceGroupName: $(resourceGroup)

# Set the environment for the deployment
# Possible values are: "production", "staging", and "development"
environment: development

# The name of the Bicep file to deploy
bicepFile: main.bicep